import { useEffect,useRef,useState } from "react";
import Character3D from "@/components/companion/Character3D";
import CharacterControls from "@/components/companion/CharacterControls";
import DownloadCodeButton from "@/components/companion/DownloadCodeButton";
import { CHARACTER_MODELS } from "@/lib/companion/companionConfig";
import { useCompanionState } from "@/lib/companion/useCompanionState";
import { getCompanionReply } from "@/lib/companion/chatEngine";
import { speakText,stopSpeaking } from "@/lib/companion/VoiceController";
import { DEFAULT_PERSONALITY } from "@/lib/companion/personality";
export default function Home(){
 const{state,setCharacterId,setAppearance,setWardrobeSlot,setEmotion,setActivity,setScene}=useCompanionState();
 const[capabilities,setCapabilities]=useState(null),[language,setLanguage]=useState("en"),[message,setMessage]=useState(""),[messages,setMessages]=useState([]),[speaking,setSpeaking]=useState(false),[mouthIntensity,setMouthIntensity]=useState(0),[busy,setBusy]=useState(false);
 const[memories,setMemories]=useState(()=>{try{return JSON.parse(localStorage.getItem("vca_memories")||"[]")}catch{return[]}}),charRef=useRef(null);
 const sendMessage=async()=>{const text=message.trim();if(!text||busy)return;setMessage("");const next=[...messages,{role:"user",text}];setMessages(next);setBusy(true);try{const result=await getCompanionReply(text,{language,history:next,memories,personality:DEFAULT_PERSONALITY});const reply=typeof result==="string"?result:result.reply;if(result?.emotion)setEmotion(result.emotion);setMessages(prev=>[...prev,{role:"assistant",text:reply}]);speakText(reply,{lang:language==="es"?"es-ES":language==="ru"?"ru-RU":language==="kk"?"kk-KZ":"en-US",onStart:()=>{setSpeaking(true);setMouthIntensity(.18)},onBoundary:()=>setMouthIntensity(.72),onEnd:()=>{setSpeaking(false);setMouthIntensity(0)},onError:()=>{setSpeaking(false);setMouthIntensity(0)}})}catch(error){setMessages(prev=>[...prev,{role:"assistant",text:"I couldn't connect to the AI service yet. The local voice demo is still available."}])}finally{setBusy(false)}};
 useEffect(()=>()=>stopSpeaking(),[]);
 return <div className="min-h-screen w-full bg-gradient-to-b from-slate-50 via-white to-slate-100 flex flex-col">
  <header className="flex items-center justify-between px-6 sm:px-10 py-6"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg bg-slate-900 grid place-items-center"><span className="text-white text-sm font-semibold">V</span></div><span className="text-slate-900 font-semibold tracking-tight">Virtual Companion AI</span></div><div className="flex items-center gap-2"><span className="text-xs sm:text-sm text-slate-500 hidden sm:inline">3D Character · Studio</span><DownloadCodeButton/></div></header>
  <main className="flex-1 flex flex-col items-center px-4 pb-10"><div className="w-full max-w-5xl">
   <div className="text-center mb-6"><h1 className="text-3xl sm:text-5xl font-semibold tracking-tight text-slate-900">Your virtual companion</h1><p className="mt-3 text-slate-500 max-w-xl mx-auto">Un personaje 3D femenino adulto y ficticio: rota la cámara y haz zoom, personaliza su apariencia y vestuario, y elige actividades, emociones y escenarios. Haz clic sobre ella para que te salude.</p></div>
   <div className="mb-4 flex justify-center gap-2" role="group" aria-label="Seleccionar personaje">{Object.values(CHARACTER_MODELS).map(character=>{const active=state.characterId===character.id;return <button key={character.id} type="button" onClick={()=>setCharacterId(character.id)} aria-pressed={active} className={`rounded-full px-4 py-2 text-sm border transition ${active?"bg-slate-900 text-white border-slate-900":"bg-white text-slate-600 border-slate-200 hover:border-slate-400"}`}>{character.label}</button>})}</div>
   <div className="relative rounded-3xl overflow-hidden border border-slate-200 shadow-xl"><div className="aspect-[4/3] sm:aspect-[16/10] w-full"><Character3D ref={charRef} className="w-full h-full" characterId={state.characterId} appearance={state.appearance} wardrobe={state.wardrobe} emotion={state.emotion} activity={state.activity} scene={state.scene} onCapabilities={setCapabilities} speaking={speaking} mouthIntensity={mouthIntensity}/></div><div className="absolute top-4 right-4 flex gap-2"><button type="button" onClick={()=>charRef.current?.zoomToFace()} className="rounded-full bg-white/85 backdrop-blur px-3 py-2 text-xs font-medium text-slate-700 border border-white/70 shadow-sm">🔍 Face close-up</button><button type="button" onClick={()=>charRef.current?.resetCamera()} className="rounded-full bg-white/85 backdrop-blur px-3 py-2 text-xs font-medium text-slate-700 border border-white/70 shadow-sm">↺ Full view</button></div><div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-full bg-white/70 backdrop-blur px-3 py-1.5 text-xs text-slate-600 border border-white/60"><span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"/>Online</div></div>
   <section className="mt-5 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Talk to your companion</h2><p className="text-xs text-slate-500">AI + device voice + facial lip-sync. Local memory stores only what you choose to keep.</p></div><select value={language} onChange={e=>setLanguage(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="en">English</option><option value="es">Español</option><option value="ru">Русский</option><option value="kk">Қазақша</option></select></div>
   <div className="mt-3 max-h-48 overflow-auto space-y-2">{messages.length===0&&<p className="text-sm text-slate-400">Write a message to start.</p>}{messages.map((m,i)=><div key={i} className={`rounded-2xl px-3 py-2 text-sm ${m.role==="user"?"ml-8 bg-slate-100 text-slate-800":"mr-8 bg-slate-900 text-white"}`}>{m.text}</div>)}</div>
   <div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>{memories.length} memoria{memories.length===1?"":"s"} local{memories.length===1?"":"es"}</span><button type="button" onClick={()=>{const value=window.prompt("Add a memory for your companion:");if(value?.trim()){const nextMemories=[...memories,value.trim()].slice(-20);setMemories(nextMemories);localStorage.setItem("vca_memories",JSON.stringify(nextMemories));}}} className="rounded-lg border border-slate-200 px-2 py-1">Add memory</button>{memories.length>0&&<button type="button" onClick={()=>{setMemories([]);localStorage.removeItem("vca_memories")}} className="rounded-lg border border-slate-200 px-2 py-1">Clear memory</button>}</div>
   <div className="mt-3 flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendMessage()} placeholder="Write to your companion..." className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-slate-500"/><button disabled={busy} onClick={sendMessage} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy?"…":"Enviar"}</button>{speaking&&<button onClick={()=>{stopSpeaking();setSpeaking(false);setMouthIntensity(0)}} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">Stop voice</button>}</div>{speaking&&<div className="mt-2 text-xs text-emerald-600">● Speaking…</div>}</section>
   <div className="mt-4"><CharacterControls state={state} capabilities={capabilities} onAppearance={setAppearance} onWardrobeSlot={setWardrobeSlot} onEmotion={setEmotion} onActivity={setActivity} onScene={setScene} onExport={format=>charRef.current?.exportModel(format)}/></div>
  </div></main>
 </div>;
}